# Generated by Django 5.2 on 2025-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('seniority', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=255)),
            ],
        ),
    ]
