# Generated by Django 5.2 on 2025-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='technologies',
            field=models.TextField(),
        ),
    ]
