# Generated by Django 5.2 on 2025-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='technologies',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='technologies',
            field=models.ManyToManyField(to='jobs.technology'),
        ),
    ]
