# Generated by Django 5.2 on 2025-05-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_technology_remove_joboffer_technologies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='technologies',
            new_name='technology',
        ),
    ]
