# Generated by Django 5.2 on 2025-05-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_technologies_joboffer_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='technology',
            new_name='technologies',
        ),
    ]
