# Generated by Django 5.2 on 2025-05-26 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
