# Generated by Django 5.2 on 2025-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_joboffer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='portal',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
